name: portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  scroll_to_index: ^3.0.1
  scrollview_observer: ^1.15.0
  cached_network_image: ^3.4.1
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.12
  easy_rich_text: ^2.0.0
  google_fonts: ^5.1.0
  device_preview: ^1.3.1
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/murshid.png"
  windows:
    generate: true
    image_path: "assets/images/murshid.png"
    icon_size: 48
  image_path: "assets/images/murshid.png"


flutter:

  uses-material-design: true


  assets:
    - assets/images/
  
  